name: wget1

on:

  schedule:
    - cron: '0 0 1 * *'
 
  workflow_dispatch: # on button click

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Backup
        run: cp -r drawabox.com/ drawabox.com.BAK/

      - name: grep
        run: grep -r "https://d15v304a6xpq4b.cloudfront.net/lesson_images" ./* > output.txt

      - name: Save
        #if: always() # Forces this to run even if wget fails
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
