name: images

on:

  schedule:
    - cron: '0 0 2 * *'
 
  workflow_dispatch: # on button click

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: grep
        run: |
          rm links2.txt
          grep -r -o 'https://d15v304a6xpq4b\.cloudfront\.net/lesson_images[^"]*' ./drawabox.com/* > links2.txt
          sed -i 's/\.\/drawabox\.com\/.*\.html://g' links2.txt
          sed -i 's/.).*//g' links2.txt
          sort -u -o links2.txt links2.txt

 #     - name: Wget
#        run: wget -r --level=5 --reject js --adjust-extension --page-requisites --content-on-error=off --local-encoding=UTF-8 --no-parent -k --retry-on-http-error=429 --wait=10 --random-wait -i links2.txt

      - name: Save
        #if: always() # Forces this to run even if wget fails
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
