name: wget1

on:

  schedule:
    - cron: '0 0 1 * *'
 
  workflow_dispatch: # on button click

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Backup
        run: cp -r drawabox.com/ drawabox.com.BAK/

      - name: Wget scrape links
        run: wget --spider -r --no-parent --no-check-certificate --retry-on-http-error=429 --wait=10 --random-wait -i links1.txt 2>&1 | grep -E -o "(http|https)://[a-zA-Z0-9./?=_-]*" | sort -u

      - name: Wget
        run: wget -r --level=5 --reject js --adjust-extension --page-requisites --content-on-error=off --local-encoding=UTF-8 --no-parent -k --retry-on-http-error=429 --wait=10 --random-wait -i links1.txt

      - name: Save
        #if: always() # Forces this to run even if wget fails
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
